name: Java CI with Gradle

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  build:
    # 실행 환경 지정
    runs-on: ubuntu-latest
    # Task의 sequence를 명시한다.
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: gradlew 에 실행 권한 부여
        run: chmod +x ./gradlew
      - run: mkdir -p ./src/main/resources/
      - run: touch ./src/main/resources/application.properties
      - run: echo "${{ secrets.PROPERTIES }}" >> ./src/main/resources/application.properties
      - run: cat ./src/main/resources/application.properties
      - name: Build with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew build
          ./gradlew test

