name: Java CI with Gradle

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Gradle Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Create src/main/resources directory
        run: mkdir -p ./src/main/resources/

      - name: Create application.properties
        run: touch ./src/main/resources/application.properties

      - name: Create PKCS12 file
        run: |
          echo "${{ secrets.PKCS12_SECRET }}" | base64 --decode > ./src/main/resources/certificate.p12

      - name: Inject jasypt key
        run: echo "jasypt.password=${{ secrets.JASYPT }}" >> ./src/main/resources/application.properties

      - name: Append PROPERTIES secret
        run: echo "${{ secrets.PROPERTIES }}" >> ./src/main/resources/application.properties

      - name: Display application.properties content
        run: cat ./src/main/resources/application.properties

      - name: Build with Gradle
        run: ./gradlew build -x test
