name: Java CI with Gradle

on:
  push:
    branches: [ "develop" ]
  pull_request_target:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  build:
    # 실행 환경 지정
    runs-on: ubuntu-latest
    environment:
      name: Danim # 변경할 환경의 이름
    # Task의 sequence를 명시한다.
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - run: mkdir -p ./src/main/resources/
      - run: touch ./src/main/resources/application.properties
      - name: jasypt key주입
        run: echo "jasypt.password=${{ secrets.JASYPT }}" >> ./src/main/resources/application.properties
      - run: echo "${{ secrets.PROPERTIES }}" >> ./src/main/resources/application.properties
      - run: cat ./src/main/resources/application.properties
      - name: Build
        run: ./gradlew build
        env:
          JASYPT_PASSWORD: ${{ secrets.JASYPT }}
      - name: Test
        run: ./gradlew test
        env:
          JASYPT_PASSWORD: ${{ secrets.JASYPT }}

