name: Java CI/CD with Gradle and Docker

on:
  push:
    branches:
      - develop
      - 'develop/**'

#  pull_request_target:
#    branches: [ "develop" ]
# 하지마...

permissions:
  contents: read

jobs:
  build:
    # 실행 환경 지정
    runs-on: ubuntu-latest
    environment:
      name: Danim # 변경할 환경의 이름
    # Task의 sequence를 명시한다.
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # gradle caching - 빌드 시간 향상
      - name: Gradle Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
            

      - run: mkdir -p ./src/main/resources/
      - run: touch ./src/main/resources/application.properties
      - name: jasypt key주입
        run: echo "jasypt.password=${{ secrets.JASYPT }}" >> ./src/main/resources/application.properties
      - run: echo "${{ secrets.PROPERTIES }}" >> ./src/main/resources/application.properties
      - run: cat ./src/main/resources/application.properties
        # gradle build
      - name: Build with Gradle
        run: ./gradlew build -x test
