name: Java CI with Gradle

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  build:
    # 실행 환경 지정
    runs-on: ubuntu-latest
    # Task의 sequence를 명시한다.
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - run: mkdir -p ./src/main/resources/
      - run: touch ./src/main/resources/application.properties
      - name: jasypt key주입
        run: echo "${{secrets.JASYPT}}" >> ./src/main/resources/application.properties
      - run: echo "${{ secrets.PROPERTIES }}" >> ./src/main/resources/application.properties
      - run: cat ./src/main/resources/application.properties
      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build
        env:
          JASYPT_PASSWORD: ${{ secrets.JASYPT }}
